[2017-11-15 11:05:06] [INFO] itemcode_2760
[2017-11-15 11:05:06] [INFO] token_Nz647p6jsdDS7a1aIT0JCH8ERCxcoV2
[2017-11-15 11:05:06] [INFO] ===XUNMA RESTURN:False:Session 过期
[2017-11-15 11:05:10] [INFO] itemcode_2760
[2017-11-15 11:05:10] [INFO] token_v0JR5WlFB2ZG49OKvmzeneDNgV8JAB29
[2017-11-15 11:05:11] [INFO] ===XUNMA RESTURN:13136438240;
[2017-11-15 13:15:49] [INFO] itemcode_2760
[2017-11-15 13:15:49] [INFO] token_v0JR5WlFB2ZG49OKvmzeneDNgV8JAB29
[2017-11-15 13:15:49] [INFO] ===XUNMA RESTURN:False:Session 过期
[2017-11-15 13:15:53] [INFO] itemcode_2760
[2017-11-15 13:15:53] [INFO] token_hKYb985gZh3iN4vqn2fBLltGqUv5Qg70
[2017-11-15 13:15:53] [INFO] ===XUNMA RESTURN:13002626409;
[2017-11-15 13:16:48] [INFO] 开始获取验证码：13002626409, wechat_register
[2017-11-15 13:16:51] [INFO] 收到消息：NOTION&单笔充值满 50元送 5%单笔充值满100元送10%自动赠送！上不封顶！-------------------------运营商选择  移动、联通或电信，不会出17号段-------------------------平台号码收到短信扣费,收不到短信不会扣费。[End]MSG&2760&13002626409&【发自易信】易信验证码为：2196，请勿将验证码提供给他人。[End]
[2017-11-15 13:16:51] [INFO] 切分消息：NOTION&单笔充值满 50元送 5%单笔充值满100元送10%自动赠送！上不封顶！-------------------------运营商选择  移动、联通或电信，不会出17号段-------------------------平台号码收到短信扣费,收不到短信不会扣费。
[2017-11-15 13:16:51] [INFO] 切分消息：MSG&2760&13002626409&【发自易信】易信验证码为：2196，请勿将验证码提供给他人。
[2017-11-15 13:16:54] [INFO] 收到消息：USER&77.531&500&3000&1500&0.8&18.929[End]RES&2760&13002626409[End]
[2017-11-15 13:16:54] [INFO] 切分消息：USER&77.531&500&3000&1500&0.8&18.929
[2017-11-15 13:16:54] [INFO] 切分消息：RES&2760&13002626409
[2017-11-15 13:16:58] [INFO] 收到消息：Null
[2017-11-15 13:16:58] [INFO] 切分消息：Null
[2017-11-15 13:17:01] [INFO] 收到消息：Null
[2017-11-15 13:17:01] [INFO] 切分消息：Null
[2017-11-15 13:17:04] [INFO] 收到消息：Null
[2017-11-15 13:17:04] [INFO] 切分消息：Null
[2017-11-15 13:17:07] [INFO] 收到消息：Null
[2017-11-15 13:17:07] [INFO] 切分消息：Null
[2017-11-15 13:17:10] [INFO] 收到消息：Null
[2017-11-15 13:17:10] [INFO] 切分消息：Null
[2017-11-15 13:41:35] [INFO] itemcode_2760
[2017-11-15 13:41:35] [INFO] token_hKYb985gZh3iN4vqn2fBLltGqUv5Qg70
[2017-11-15 13:41:35] [INFO] ===XUNMA RESTURN:False:Session 过期
[2017-11-15 13:41:39] [INFO] itemcode_2760
[2017-11-15 13:41:39] [INFO] token_OHjS4wOteBezcptiCc4UEGHPWBRVwJ18
[2017-11-15 13:41:39] [INFO] ===XUNMA RESTURN:15982845059;
[2017-11-15 13:41:51] [INFO] itemcode_2760
[2017-11-15 13:41:51] [INFO] token_OHjS4wOteBezcptiCc4UEGHPWBRVwJ18
[2017-11-15 13:41:51] [INFO] ===XUNMA RESTURN:18227184330;
[2017-11-15 13:42:05] [INFO] itemcode_2760
[2017-11-15 13:42:05] [INFO] token_OHjS4wOteBezcptiCc4UEGHPWBRVwJ18
[2017-11-15 13:42:05] [INFO] ===XUNMA RESTURN:18280427782;
[2017-11-15 13:42:19] [INFO] itemcode_2760
[2017-11-15 13:42:19] [INFO] token_OHjS4wOteBezcptiCc4UEGHPWBRVwJ18
[2017-11-15 13:42:19] [INFO] ===XUNMA RESTURN:17098244615;
[2017-11-15 13:42:29] [INFO] 开始获取验证码：17098244615, wechat_register
[2017-11-15 13:42:32] [INFO] 收到消息：NOTION&单笔充值满 50元送 5%单笔充值满100元送10%自动赠送！上不封顶！-------------------------运营商选择  移动、联通或电信，不会出17号段-------------------------平台号码收到短信扣费,收不到短信不会扣费。[End]
[2017-11-15 13:42:32] [INFO] 切分消息：NOTION&单笔充值满 50元送 5%单笔充值满100元送10%自动赠送！上不封顶！-------------------------运营商选择  移动、联通或电信，不会出17号段-------------------------平台号码收到短信扣费,收不到短信不会扣费。
[2017-11-15 13:42:35] [INFO] 收到消息：Null
[2017-11-15 13:42:35] [INFO] 切分消息：Null
[2017-11-15 13:42:39] [INFO] 收到消息：Null
[2017-11-15 13:42:39] [INFO] 切分消息：Null
[2017-11-15 13:42:42] [INFO] 收到消息：Null
[2017-11-15 13:42:42] [INFO] 切分消息：Null
[2017-11-15 13:42:45] [INFO] 收到消息：Null
[2017-11-15 13:42:45] [INFO] 切分消息：Null
[2017-11-15 13:42:48] [INFO] 收到消息：Null
[2017-11-15 13:42:48] [INFO] 切分消息：Null
[2017-11-15 13:42:51] [INFO] 收到消息：Null
[2017-11-15 13:42:51] [INFO] 切分消息：Null
[2017-11-15 13:42:54] [INFO] 收到消息：Null
[2017-11-15 13:42:54] [INFO] 切分消息：Null
[2017-11-15 13:42:57] [INFO] 收到消息：Null
[2017-11-15 13:42:57] [INFO] 切分消息：Null
[2017-11-15 13:43:01] [INFO] 收到消息：Null
[2017-11-15 13:43:01] [INFO] 切分消息：Null
[2017-11-15 13:43:04] [INFO] 收到消息：Null
[2017-11-15 13:43:04] [INFO] 切分消息：Null
[2017-11-15 13:43:07] [INFO] 收到消息：Null
[2017-11-15 13:43:07] [INFO] 切分消息：Null
[2017-11-15 13:43:10] [INFO] 收到消息：Null
[2017-11-15 13:43:10] [INFO] 切分消息：Null
[2017-11-15 13:43:13] [INFO] 收到消息：Null
[2017-11-15 13:43:13] [INFO] 切分消息：Null
[2017-11-15 13:43:16] [INFO] 收到消息：MSG&2760&17098244615&【发自易信】易信验证码为：4501，请勿将验证码提供给他人。[End]
[2017-11-15 13:43:16] [INFO] 切分消息：MSG&2760&17098244615&【发自易信】易信验证码为：4501，请勿将验证码提供给他人。
[2017-11-15 13:43:16] [INFO] KEY: verify_code_2760_17098244615, Code: 4501
[2017-11-15 13:46:25] [INFO] itemcode_2760
[2017-11-15 13:46:25] [INFO] token_OHjS4wOteBezcptiCc4UEGHPWBRVwJ18
[2017-11-15 13:46:25] [INFO] ===XUNMA RESTURN:13175835479;
[2017-11-15 13:46:36] [INFO] 开始获取验证码：13175835479, wechat_register
[2017-11-15 13:46:39] [INFO] 收到消息：USER&77.451&500&3000&1500&0.8&18.929[End]
[2017-11-15 13:46:39] [INFO] 切分消息：USER&77.451&500&3000&1500&0.8&18.929
[2017-11-15 13:46:42] [INFO] 收到消息：Null
[2017-11-15 13:46:42] [INFO] 切分消息：Null
[2017-11-15 13:46:45] [INFO] 收到消息：Null
[2017-11-15 13:46:45] [INFO] 切分消息：Null
[2017-11-15 13:46:48] [INFO] 收到消息：Null
[2017-11-15 13:46:48] [INFO] 切分消息：Null
[2017-11-15 13:46:51] [INFO] 收到消息：Null
[2017-11-15 13:46:51] [INFO] 切分消息：Null
[2017-11-15 13:46:54] [INFO] 收到消息：Null
[2017-11-15 13:46:54] [INFO] 切分消息：Null
[2017-11-15 13:46:58] [INFO] 收到消息：Null
[2017-11-15 13:46:58] [INFO] 切分消息：Null
[2017-11-15 13:47:01] [INFO] 收到消息：Null
[2017-11-15 13:47:01] [INFO] 切分消息：Null
[2017-11-15 13:47:04] [INFO] 收到消息：Null
[2017-11-15 13:47:04] [INFO] 切分消息：Null
[2017-11-15 13:47:07] [INFO] 收到消息：Null
[2017-11-15 13:47:07] [INFO] 切分消息：Null
[2017-11-15 13:47:10] [INFO] 收到消息：Null
[2017-11-15 13:47:10] [INFO] 切分消息：Null
[2017-11-15 13:47:13] [INFO] 收到消息：Null
[2017-11-15 13:47:13] [INFO] 切分消息：Null
[2017-11-15 13:47:16] [INFO] 收到消息：Null
[2017-11-15 13:47:16] [INFO] 切分消息：Null
[2017-11-15 13:47:19] [INFO] 收到消息：Null
[2017-11-15 13:47:19] [INFO] 切分消息：Null
[2017-11-15 13:47:23] [INFO] 收到消息：Null
[2017-11-15 13:47:23] [INFO] 切分消息：Null
[2017-11-15 13:47:26] [INFO] 收到消息：Null
[2017-11-15 13:47:26] [INFO] 切分消息：Null
[2017-11-15 13:47:29] [INFO] 收到消息：Null
[2017-11-15 13:47:29] [INFO] 切分消息：Null
[2017-11-15 13:47:32] [INFO] 收到消息：Null
[2017-11-15 13:47:32] [INFO] 切分消息：Null
[2017-11-15 13:47:35] [INFO] 收到消息：Null
[2017-11-15 13:47:35] [INFO] 切分消息：Null
[2017-11-15 13:48:17] [INFO] itemcode_2760
[2017-11-15 13:48:17] [INFO] token_OHjS4wOteBezcptiCc4UEGHPWBRVwJ18
[2017-11-15 13:48:17] [INFO] ===XUNMA RESTURN:13216597945;
[2017-11-15 13:48:28] [INFO] 开始获取验证码：13216597945, wechat_register
[2017-11-15 13:48:31] [INFO] 收到消息：MSG&2760&13216597945&【发自易信】易信验证码为：9666，请勿将验证码提供给他人。[End]
[2017-11-15 13:48:31] [INFO] 切分消息：MSG&2760&13216597945&【发自易信】易信验证码为：9666，请勿将验证码提供给他人。
[2017-11-15 13:48:31] [INFO] KEY: verify_code_2760_13216597945, Code: 9666
[2017-11-15 14:00:40] [INFO] itemcode_2760
[2017-11-15 14:00:40] [INFO] token_OHjS4wOteBezcptiCc4UEGHPWBRVwJ18
[2017-11-15 14:00:40] [INFO] ===XUNMA RESTURN:False:Session 过期
[2017-11-15 14:00:44] [INFO] itemcode_2760
[2017-11-15 14:00:44] [INFO] token_T3Fd18jtaEan26KaiIP25acIcykoLE5
[2017-11-15 14:00:44] [INFO] ===XUNMA RESTURN:17155943161;
[2017-11-15 14:00:54] [INFO] 开始获取验证码：17155943161, wechat_register
[2017-11-15 14:00:58] [INFO] 收到消息：NOTION&单笔充值满 50元送 5%单笔充值满100元送10%自动赠送！上不封顶！-------------------------运营商选择  移动、联通或电信，不会出17号段-------------------------平台号码收到短信扣费,收不到短信不会扣费。[End]MSG&2760&17155943161&【发自易信】易信验证码为：9044，请勿将验证码提供给他人。[End]
[2017-11-15 14:00:58] [INFO] 切分消息：NOTION&单笔充值满 50元送 5%单笔充值满100元送10%自动赠送！上不封顶！-------------------------运营商选择  移动、联通或电信，不会出17号段-------------------------平台号码收到短信扣费,收不到短信不会扣费。
[2017-11-15 14:00:58] [INFO] 切分消息：MSG&2760&17155943161&【发自易信】易信验证码为：9044，请勿将验证码提供给他人。
[2017-11-15 14:00:58] [INFO] KEY: verify_code_2760_17155943161, Code: 9044
[2017-11-15 14:05:52] [INFO] itemcode_2760
[2017-11-15 14:05:52] [INFO] token_T3Fd18jtaEan26KaiIP25acIcykoLE5
[2017-11-15 14:05:52] [INFO] ===XUNMA RESTURN:15828448821;
[2017-11-15 14:06:03] [INFO] itemcode_2760
[2017-11-15 14:06:03] [INFO] token_T3Fd18jtaEan26KaiIP25acIcykoLE5
[2017-11-15 14:06:03] [INFO] ===XUNMA RESTURN:13175813646;
[2017-11-15 14:06:14] [INFO] 开始获取验证码：13175813646, wechat_register
[2017-11-15 14:06:17] [INFO] 收到消息：USER&77.291&500&3000&1500&0.8&18.929[End]MSG&2760&13175813646&【发自易信】易信验证码为：4598，请勿将验证码提供给他人。[End]
[2017-11-15 14:06:17] [INFO] 切分消息：USER&77.291&500&3000&1500&0.8&18.929
[2017-11-15 14:06:17] [INFO] 切分消息：MSG&2760&13175813646&【发自易信】易信验证码为：4598，请勿将验证码提供给他人。
[2017-11-15 14:06:17] [INFO] KEY: verify_code_2760_13175813646, Code: 4598
[2017-11-15 15:18:49] [INFO] itemcode_2760
[2017-11-15 15:18:49] [INFO] token_T3Fd18jtaEan26KaiIP25acIcykoLE5
[2017-11-15 15:18:54] [INFO] ===XUNMA RESTURN:False:Session 过期
[2017-11-15 15:18:58] [INFO] itemcode_2760
[2017-11-15 15:18:58] [INFO] token_CXBX1csPfCZwboxFxRUrZT7BP3sMVr14
[2017-11-15 15:18:58] [INFO] ===XUNMA RESTURN:15882104125;
[2017-11-15 15:19:09] [INFO] itemcode_2760
[2017-11-15 15:19:09] [INFO] token_CXBX1csPfCZwboxFxRUrZT7BP3sMVr14
[2017-11-15 15:19:10] [INFO] ===XUNMA RESTURN:17083433143;
[2017-11-15 15:19:20] [INFO] 开始获取验证码：17083433143, wechat_register
[2017-11-15 15:19:24] [INFO] 收到消息：NOTION&单笔充值满 50元送 5%单笔充值满100元送10%自动赠送！上不封顶！-------------------------运营商选择  移动、联通或电信，不会出17号段-------------------------平台号码收到短信扣费,收不到短信不会扣费。[End]
[2017-11-15 15:19:24] [INFO] 切分消息：NOTION&单笔充值满 50元送 5%单笔充值满100元送10%自动赠送！上不封顶！-------------------------运营商选择  移动、联通或电信，不会出17号段-------------------------平台号码收到短信扣费,收不到短信不会扣费。
[2017-11-15 15:19:27] [INFO] 收到消息：MSG&2760&17083433143&【发自易信】易信验证码为：8147，请勿将验证码提供给他人。[End]
[2017-11-15 15:19:27] [INFO] 切分消息：MSG&2760&17083433143&【发自易信】易信验证码为：8147，请勿将验证码提供给他人。
[2017-11-15 15:19:27] [INFO] KEY: verify_code_2760_17083433143, Code: 8147
[2017-11-15 16:45:29] [INFO] itemcode_2760
[2017-11-15 16:45:29] [INFO] token_H1QHRTJ0Jm4sqjrmBP1gf0JUu5rFAW71
[2017-11-15 16:45:29] [INFO] ===XUNMA RESTURN:False:Session 过期
[2017-11-15 16:45:33] [INFO] itemcode_2760
[2017-11-15 16:45:33] [INFO] token_JkyRSeqfiQ7Sj4c4O5zFswMB3LZDPr21
[2017-11-15 16:45:33] [INFO] ===XUNMA RESTURN:18478351982;
[2017-11-15 16:45:59] [INFO] itemcode_2760
[2017-11-15 16:45:59] [INFO] token_JkyRSeqfiQ7Sj4c4O5zFswMB3LZDPr21
[2017-11-15 16:45:59] [INFO] ===XUNMA RESTURN:18224052880;
[2017-11-15 16:46:17] [INFO] itemcode_2760
[2017-11-15 16:46:17] [INFO] token_JkyRSeqfiQ7Sj4c4O5zFswMB3LZDPr21
[2017-11-15 16:46:17] [INFO] ===XUNMA RESTURN:18200247593;
[2017-11-18 15:04:12] [INFO] itemcode_2760
[2017-11-18 15:04:12] [INFO] token_JkyRSeqfiQ7Sj4c4O5zFswMB3LZDPr21
[2017-11-18 15:04:12] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2017-11-18 15:04:12] [INFO] itemcode_2760
[2017-11-18 15:04:12] [INFO] token_JkyRSeqfiQ7Sj4c4O5zFswMB3LZDPr21
[2017-11-18 15:04:12] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2017-11-18 15:04:12] [INFO] itemcode_2760
[2017-11-18 15:04:12] [INFO] token_JkyRSeqfiQ7Sj4c4O5zFswMB3LZDPr21
[2017-11-18 15:04:12] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2017-11-18 15:04:12] [INFO] itemcode_2760
[2017-11-18 15:04:12] [INFO] token_JkyRSeqfiQ7Sj4c4O5zFswMB3LZDPr21
[2017-11-18 15:04:12] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2017-11-18 15:04:12] [INFO] itemcode_2760
[2017-11-18 15:04:12] [INFO] token_JkyRSeqfiQ7Sj4c4O5zFswMB3LZDPr21
[2017-11-18 15:04:12] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2017-11-18 15:04:12] [INFO] itemcode_2760
[2017-11-18 15:04:12] [INFO] token_JkyRSeqfiQ7Sj4c4O5zFswMB3LZDPr21
[2017-11-18 15:04:17] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2017-11-18 15:04:17] [INFO] itemcode_2760
[2017-11-18 15:04:17] [INFO] token_JkyRSeqfiQ7Sj4c4O5zFswMB3LZDPr21
[2017-11-18 15:04:17] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2017-11-18 15:04:17] [INFO] itemcode_2760
[2017-11-18 15:04:17] [INFO] token_JkyRSeqfiQ7Sj4c4O5zFswMB3LZDPr21
[2017-11-18 15:04:17] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2017-11-18 15:04:17] [INFO] itemcode_2760
[2017-11-18 15:04:17] [INFO] token_JkyRSeqfiQ7Sj4c4O5zFswMB3LZDPr21
[2017-11-18 15:04:17] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2017-11-18 15:04:17] [INFO] itemcode_2760
[2017-11-18 15:04:17] [INFO] token_JkyRSeqfiQ7Sj4c4O5zFswMB3LZDPr21
[2017-11-18 15:04:17] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2017-11-18 15:04:17] [INFO] itemcode_2760
[2017-11-18 15:04:17] [INFO] token_JkyRSeqfiQ7Sj4c4O5zFswMB3LZDPr21
[2017-11-18 15:04:17] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2017-11-18 15:04:17] [INFO] itemcode_2760
[2017-11-18 15:04:17] [INFO] token_JkyRSeqfiQ7Sj4c4O5zFswMB3LZDPr21
[2017-11-18 15:04:17] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2017-11-18 15:04:17] [INFO] itemcode_2760
[2017-11-18 15:04:17] [INFO] token_JkyRSeqfiQ7Sj4c4O5zFswMB3LZDPr21
[2017-11-18 15:04:17] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2017-11-18 15:04:17] [INFO] itemcode_2760
[2017-11-18 15:04:17] [INFO] token_JkyRSeqfiQ7Sj4c4O5zFswMB3LZDPr21
[2017-11-18 15:04:17] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2017-11-18 15:04:17] [INFO] itemcode_2760
[2017-11-18 15:04:17] [INFO] token_JkyRSeqfiQ7Sj4c4O5zFswMB3LZDPr21
[2017-11-18 15:04:17] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2017-11-18 15:04:17] [INFO] itemcode_2760
[2017-11-18 15:04:17] [INFO] token_JkyRSeqfiQ7Sj4c4O5zFswMB3LZDPr21
[2017-11-18 15:04:17] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2017-11-18 15:04:17] [INFO] itemcode_2760
[2017-11-18 15:04:17] [INFO] token_JkyRSeqfiQ7Sj4c4O5zFswMB3LZDPr21
[2017-11-18 15:04:17] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2017-11-18 15:04:17] [INFO] itemcode_2760
[2017-11-18 15:04:17] [INFO] token_JkyRSeqfiQ7Sj4c4O5zFswMB3LZDPr21
[2017-11-18 15:04:17] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2017-11-18 15:04:17] [INFO] itemcode_2760
[2017-11-18 15:04:17] [INFO] token_JkyRSeqfiQ7Sj4c4O5zFswMB3LZDPr21
[2017-11-18 15:04:17] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2017-11-18 15:04:17] [INFO] itemcode_2760
[2017-11-18 15:04:17] [INFO] token_JkyRSeqfiQ7Sj4c4O5zFswMB3LZDPr21
[2017-11-18 15:04:17] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2017-11-18 15:04:17] [INFO] itemcode_2760
[2017-11-18 15:04:17] [INFO] token_JkyRSeqfiQ7Sj4c4O5zFswMB3LZDPr21
[2017-11-18 15:04:17] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2017-11-18 15:04:17] [INFO] itemcode_2760
[2017-11-18 15:04:17] [INFO] token_JkyRSeqfiQ7Sj4c4O5zFswMB3LZDPr21
[2017-11-18 15:04:17] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2017-11-18 15:04:17] [INFO] itemcode_2760
[2017-11-18 15:04:17] [INFO] token_JkyRSeqfiQ7Sj4c4O5zFswMB3LZDPr21
[2017-11-18 15:04:17] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2017-11-18 15:04:17] [INFO] itemcode_2760
[2017-11-18 15:04:17] [INFO] token_JkyRSeqfiQ7Sj4c4O5zFswMB3LZDPr21
[2017-11-18 15:04:18] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2017-11-18 15:04:18] [INFO] itemcode_2760
[2017-11-18 15:04:18] [INFO] token_JkyRSeqfiQ7Sj4c4O5zFswMB3LZDPr21
[2017-11-18 15:04:18] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2017-11-18 15:04:18] [INFO] itemcode_2760
[2017-11-18 15:04:18] [INFO] token_JkyRSeqfiQ7Sj4c4O5zFswMB3LZDPr21
[2017-11-18 15:04:18] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2017-11-18 15:04:18] [INFO] itemcode_2760
[2017-11-18 15:04:18] [INFO] token_JkyRSeqfiQ7Sj4c4O5zFswMB3LZDPr21
[2017-11-18 15:04:18] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2017-11-18 15:04:18] [INFO] itemcode_2760
[2017-11-18 15:04:18] [INFO] token_JkyRSeqfiQ7Sj4c4O5zFswMB3LZDPr21
[2017-11-18 15:04:18] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2017-11-18 15:04:18] [INFO] itemcode_2760
[2017-11-18 15:04:18] [INFO] token_JkyRSeqfiQ7Sj4c4O5zFswMB3LZDPr21
[2017-11-18 15:04:18] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2017-11-18 15:04:18] [INFO] itemcode_2760
[2017-11-18 15:04:18] [INFO] token_JkyRSeqfiQ7Sj4c4O5zFswMB3LZDPr21
[2017-11-18 15:04:18] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2017-11-19 16:22:50] [INFO] ===SERVER RESTURN:1|17187497685
[2017-11-23 13:24:27] [INFO] ===SERVER RESTURN:0|系统没有找到此号码
[2017-11-23 13:24:30] [INFO] ===SERVER RESTURN:0|系统没有找到此号码
[2017-11-23 13:24:33] [INFO] ===SERVER RESTURN:0|系统没有找到此号码
[2017-11-23 13:24:36] [INFO] ===SERVER RESTURN:0|系统没有找到此号码
[2017-11-23 13:24:40] [INFO] ===SERVER RESTURN:0|系统没有找到此号码
[2017-11-23 13:24:43] [INFO] ===SERVER RESTURN:0|系统没有找到此号码
[2017-11-23 13:24:46] [INFO] ===SERVER RESTURN:0|系统没有找到此号码
[2017-11-23 13:24:49] [INFO] ===SERVER RESTURN:0|系统没有找到此号码
[2017-11-23 13:24:52] [INFO] ===SERVER RESTURN:0|系统没有找到此号码
[2017-11-23 13:24:56] [INFO] ===SERVER RESTURN:0|系统没有找到此号码
[2017-11-23 13:24:59] [INFO] ===SERVER RESTURN:0|系统没有找到此号码
[2017-11-23 13:25:02] [INFO] ===SERVER RESTURN:0|系统没有找到此号码
[2017-11-23 13:25:05] [INFO] ===SERVER RESTURN:0|系统没有找到此号码
[2017-11-23 13:25:09] [INFO] ===SERVER RESTURN:0|系统没有找到此号码
[2017-11-23 13:25:12] [INFO] ===SERVER RESTURN:0|系统没有找到此号码
[2017-11-23 13:25:15] [INFO] ===SERVER RESTURN:0|系统没有找到此号码
[2017-11-23 13:25:18] [INFO] ===SERVER RESTURN:0|系统没有找到此号码
[2017-11-23 13:25:28] [INFO] ===SERVER RESTURN:0|系统没有找到此号码
[2017-11-23 13:25:36] [INFO] ===SERVER RESTURN:0|系统没有找到此号码
[2017-11-23 13:25:40] [INFO] ===SERVER RESTURN:0|系统没有找到此号码
[2017-11-23 13:25:43] [INFO] ===SERVER RESTURN:0|系统没有找到此号码
[2017-11-23 13:25:46] [INFO] ===SERVER RESTURN:0|系统没有找到此号码
[2017-11-23 13:25:49] [INFO] ===SERVER RESTURN:0|系统没有找到此号码
[2017-11-23 13:25:52] [INFO] ===SERVER RESTURN:0|系统没有找到此号码
[2017-11-23 13:26:37] [INFO] ===SERVER RESTURN:1|18474745788
[2017-11-23 13:26:53] [INFO] ===SERVER RESTURN:1|17122514876
[2017-11-25 17:07:46] [INFO] ===SERVER RESTURN:1|18906845741
[2017-11-25 17:09:40] [INFO] ===SERVER RESTURN:1|17092471303
[2017-11-25 17:11:49] [INFO] ===SERVER RESTURN:1|17098586031
[2017-11-25 17:16:00] [INFO] timed out
[2017-11-25 17:16:20] [INFO] 
[2017-11-25 17:16:26] [INFO] ===SERVER RESTURN:1|18745488726
[2018-04-27 12:29:27] [INFO] itemcode_2760
[2018-04-27 12:29:27] [INFO] token_4sZeZUd4BGR1yDNdOkCAwIVHCQdZnE32
[2018-04-27 12:29:27] [INFO] ===XUNMA RESTURN:False:Session 过期
[2018-04-27 12:29:31] [INFO] itemcode_2760
[2018-04-27 12:29:31] [INFO] token_sYlZdm76GgAQi4hEa0JL7NB1g6QLil19
[2018-04-27 12:29:31] [INFO] ===XUNMA RESTURN:False:暂时没有此项目号码，请等会试试...
[2018-04-27 13:32:51] [INFO] itemcode_2760
[2018-04-27 13:32:51] [INFO] token_sYlZdm76GgAQi4hEa0JL7NB1g6QLil19
[2018-04-27 13:32:52] [INFO] ===XUNMA RESTURN:False:Session 过期
[2018-04-27 13:32:56] [INFO] itemcode_2760
[2018-04-27 13:32:56] [INFO] token_jQj5wy1XbLo8qnAR9HVlXHogvrTnsa57
[2018-04-27 13:32:56] [INFO] ===XUNMA RESTURN:False:暂时没有此项目号码，请等会试试...
[2018-04-27 13:33:57] [INFO] itemcode_2760
[2018-04-27 13:33:57] [INFO] token_jQj5wy1XbLo8qnAR9HVlXHogvrTnsa57
[2018-04-27 13:33:57] [INFO] ===XUNMA RESTURN:False:暂时没有此项目号码，请等会试试...
[2018-04-27 13:34:26] [INFO] itemcode_2760
[2018-04-27 13:34:26] [INFO] token_jQj5wy1XbLo8qnAR9HVlXHogvrTnsa57
[2018-04-27 13:34:26] [INFO] ===XUNMA RESTURN:False:暂时没有此项目号码，请等会试试...
[2018-04-27 13:34:41] [INFO] itemcode_2760
[2018-04-27 13:34:41] [INFO] token_jQj5wy1XbLo8qnAR9HVlXHogvrTnsa57
[2018-04-27 13:34:41] [INFO] ===XUNMA RESTURN:False:暂时没有此项目号码，请等会试试...
[2018-04-27 13:36:07] [INFO] itemcode_2760
[2018-04-27 13:36:07] [INFO] token_jQj5wy1XbLo8qnAR9HVlXHogvrTnsa57
[2018-04-27 13:36:07] [INFO] ===XUNMA RESTURN:13583337946;
[2018-04-27 13:38:00] [INFO] itemcode_2760
[2018-04-27 13:38:00] [INFO] token_jQj5wy1XbLo8qnAR9HVlXHogvrTnsa57
[2018-04-27 13:38:00] [INFO] ===XUNMA RESTURN:13458591735;
[2018-04-27 13:39:24] [INFO] itemcode_2760
[2018-04-27 13:39:24] [INFO] token_jQj5wy1XbLo8qnAR9HVlXHogvrTnsa57
[2018-04-27 13:39:24] [INFO] ===XUNMA RESTURN:15719412771;
[2018-04-27 13:42:39] [INFO] itemcode_2760
[2018-04-27 13:42:39] [INFO] token_jQj5wy1XbLo8qnAR9HVlXHogvrTnsa57
[2018-04-27 13:42:39] [INFO] ===XUNMA RESTURN:15719475609;
[2018-04-27 13:43:15] [INFO] 开始获取验证码：15719475609, wechat_register
[2018-04-27 13:43:18] [INFO] 收到消息：NOTION&单笔充值满 50元送 5%单笔充值满100元送10%自动赠送！上不封顶！-------------------------运营商选择 移动、联通或电信，不会出17号段-------------------------QQ群：662853542　-------------------------[End]MSG&2760&15719475609&【易信验证码】易信验证码为：7355，请勿将验证码提供给他人。[End]
[2018-04-27 13:43:18] [INFO] 切分消息：NOTION&单笔充值满 50元送 5%单笔充值满100元送10%自动赠送！上不封顶！-------------------------运营商选择 移动、联通或电信，不会出17号段-------------------------QQ群：662853542　-------------------------
[2018-04-27 13:43:18] [INFO] 切分消息：MSG&2760&15719475609&【易信验证码】易信验证码为：7355，请勿将验证码提供给他人。
[2018-04-27 13:43:18] [INFO] KEY: verify_code_2760_15719475609, Code: 7355
[2018-04-27 13:52:14] [INFO] itemcode_2760
[2018-04-27 13:52:14] [INFO] token_jQj5wy1XbLo8qnAR9HVlXHogvrTnsa57
[2018-04-27 13:52:14] [INFO] ===XUNMA RESTURN:13458594100;
[2018-04-27 13:52:37] [INFO] 开始获取验证码：13458594100, wechat_register
[2018-04-27 13:52:40] [INFO] 收到消息：USER&17.931&500&3000&1500&0.8&18.929[End]MSG&2760&13458594100&【易信验证码】易信验证码为：2228，请勿将验证码提供给他人。[End]
[2018-04-27 13:52:40] [INFO] 切分消息：USER&17.931&500&3000&1500&0.8&18.929
[2018-04-27 13:52:40] [INFO] 切分消息：MSG&2760&13458594100&【易信验证码】易信验证码为：2228，请勿将验证码提供给他人。
[2018-04-27 13:52:40] [INFO] KEY: verify_code_2760_13458594100, Code: 2228
[2018-04-27 13:57:36] [INFO] itemcode_2760
[2018-04-27 13:57:36] [INFO] token_jQj5wy1XbLo8qnAR9HVlXHogvrTnsa57
[2018-04-27 13:57:36] [INFO] ===XUNMA RESTURN:13458577183;
[2018-04-27 13:58:17] [INFO] 开始获取验证码：13458577183, wechat_register
[2018-04-27 13:58:20] [INFO] 收到消息：USER&17.851&500&3000&1500&0.8&18.929[End]MSG&2760&13458577183&【易信验证码】易信验证码为：9414，请勿将验证码提供给他人。[End]
[2018-04-27 13:58:20] [INFO] 切分消息：USER&17.851&500&3000&1500&0.8&18.929
[2018-04-27 13:58:20] [INFO] 切分消息：MSG&2760&13458577183&【易信验证码】易信验证码为：9414，请勿将验证码提供给他人。
[2018-04-27 13:58:20] [INFO] KEY: verify_code_2760_13458577183, Code: 9414
[2018-04-27 14:03:05] [INFO] itemcode_2760
[2018-04-27 14:03:05] [INFO] token_jQj5wy1XbLo8qnAR9HVlXHogvrTnsa57
[2018-04-27 14:03:06] [INFO] ===XUNMA RESTURN:15719457967;
[2018-04-27 14:03:28] [INFO] 开始获取验证码：15719457967, wechat_register
[2018-04-27 14:03:31] [INFO] 收到消息：USER&17.771&500&3000&1500&0.8&18.929[End]MSG&2760&15719457967&【易信验证码】易信验证码为：3779，请勿将验证码提供给他人。[End]
[2018-04-27 14:03:31] [INFO] 切分消息：USER&17.771&500&3000&1500&0.8&18.929
[2018-04-27 14:03:31] [INFO] 切分消息：MSG&2760&15719457967&【易信验证码】易信验证码为：3779，请勿将验证码提供给他人。
[2018-04-27 14:03:31] [INFO] KEY: verify_code_2760_15719457967, Code: 3779
[2018-04-27 14:10:54] [INFO] itemcode_2760
[2018-04-27 14:10:54] [INFO] token_jQj5wy1XbLo8qnAR9HVlXHogvrTnsa57
[2018-04-27 14:10:54] [INFO] ===XUNMA RESTURN:13458579205;
[2018-04-27 14:11:13] [INFO] 开始获取验证码：13458579205, wechat_register
[2018-04-27 14:11:16] [INFO] 收到消息：USER&17.691&500&3000&1500&0.8&18.929[End]MSG&2760&13458579205&【易信验证码】易信验证码为：4784，请勿将验证码提供给他人。[End]
[2018-04-27 14:11:16] [INFO] 切分消息：USER&17.691&500&3000&1500&0.8&18.929
[2018-04-27 14:11:16] [INFO] 切分消息：MSG&2760&13458579205&【易信验证码】易信验证码为：4784，请勿将验证码提供给他人。
[2018-04-27 14:11:16] [INFO] KEY: verify_code_2760_13458579205, Code: 4784
[2018-04-27 14:14:50] [INFO] itemcode_2760
[2018-04-27 14:14:50] [INFO] token_jQj5wy1XbLo8qnAR9HVlXHogvrTnsa57
[2018-04-27 14:14:51] [INFO] ===XUNMA RESTURN:13458589647;
[2018-04-27 14:15:07] [INFO] 开始获取验证码：13458589647, wechat_register
[2018-04-27 14:15:10] [INFO] 收到消息：USER&17.611&500&3000&1500&0.8&18.929[End]MSG&2760&13458589647&【易信验证码】易信验证码为：7581，请勿将验证码提供给他人。[End]
[2018-04-27 14:15:10] [INFO] 切分消息：USER&17.611&500&3000&1500&0.8&18.929
[2018-04-27 14:15:10] [INFO] 切分消息：MSG&2760&13458589647&【易信验证码】易信验证码为：7581，请勿将验证码提供给他人。
[2018-04-27 14:15:10] [INFO] KEY: verify_code_2760_13458589647, Code: 7581
[2018-04-27 14:17:45] [INFO] itemcode_2760
[2018-04-27 14:17:45] [INFO] token_jQj5wy1XbLo8qnAR9HVlXHogvrTnsa57
[2018-04-27 14:17:45] [INFO] ===XUNMA RESTURN:13458597077;
[2018-04-27 14:18:19] [INFO] 开始获取验证码：13458597077, wechat_register
[2018-04-27 14:18:22] [INFO] 收到消息：USER&17.531&500&3000&1500&0.8&18.929[End]MSG&2760&13458597077&【易信验证码】易信验证码为：7224，请勿将验证码提供给他人。[End]
[2018-04-27 14:18:22] [INFO] 切分消息：USER&17.531&500&3000&1500&0.8&18.929
[2018-04-27 14:18:22] [INFO] 切分消息：MSG&2760&13458597077&【易信验证码】易信验证码为：7224，请勿将验证码提供给他人。
[2018-04-27 14:18:22] [INFO] KEY: verify_code_2760_13458597077, Code: 7224
[2018-04-27 14:20:35] [INFO] itemcode_2760
[2018-04-27 14:20:35] [INFO] token_jQj5wy1XbLo8qnAR9HVlXHogvrTnsa57
[2018-04-27 14:20:35] [INFO] ===XUNMA RESTURN:15719450395;
[2018-04-27 14:20:53] [INFO] 开始获取验证码：15719450395, wechat_register
[2018-04-27 14:20:56] [INFO] 收到消息：USER&17.451&500&3000&1500&0.8&18.929[End]MSG&2760&15719450395&【易信验证码】易信验证码为：8923，请勿将验证码提供给他人。[End]
[2018-04-27 14:20:56] [INFO] 切分消息：USER&17.451&500&3000&1500&0.8&18.929
[2018-04-27 14:20:56] [INFO] 切分消息：MSG&2760&15719450395&【易信验证码】易信验证码为：8923，请勿将验证码提供给他人。
[2018-04-27 14:20:56] [INFO] KEY: verify_code_2760_15719450395, Code: 8923
[2018-04-27 14:24:01] [INFO] itemcode_2760
[2018-04-27 14:24:01] [INFO] token_jQj5wy1XbLo8qnAR9HVlXHogvrTnsa57
[2018-04-27 14:24:01] [INFO] ===XUNMA RESTURN:15719475501;
[2018-04-27 14:24:15] [INFO] 开始获取验证码：15719475501, wechat_register
[2018-04-27 14:24:19] [INFO] 收到消息：USER&17.371&500&3000&1500&0.8&18.929[End]MSG&2760&15719475501&【易信验证码】易信验证码为：1218，请勿将验证码提供给他人。[End]
[2018-04-27 14:24:19] [INFO] 切分消息：USER&17.371&500&3000&1500&0.8&18.929
[2018-04-27 14:24:19] [INFO] 切分消息：MSG&2760&15719475501&【易信验证码】易信验证码为：1218，请勿将验证码提供给他人。
[2018-04-27 14:24:19] [INFO] KEY: verify_code_2760_15719475501, Code: 1218
[2018-04-27 14:26:00] [INFO] itemcode_2760
[2018-04-27 14:26:00] [INFO] token_jQj5wy1XbLo8qnAR9HVlXHogvrTnsa57
[2018-04-27 14:26:00] [INFO] ===XUNMA RESTURN:15719478044;
[2018-04-27 14:26:31] [INFO] 开始获取验证码：15719478044, wechat_register
[2018-04-27 14:26:34] [INFO] 收到消息：USER&17.291&500&3000&1500&0.8&18.929[End]MSG&2760&15719478044&【易信验证码】易信验证码为：4558，请勿将验证码提供给他人。[End]
[2018-04-27 14:26:34] [INFO] 切分消息：USER&17.291&500&3000&1500&0.8&18.929
[2018-04-27 14:26:34] [INFO] 切分消息：MSG&2760&15719478044&【易信验证码】易信验证码为：4558，请勿将验证码提供给他人。
[2018-04-27 14:26:34] [INFO] KEY: verify_code_2760_15719478044, Code: 4558
[2018-04-27 14:46:26] [INFO] itemcode_2760
[2018-04-27 14:46:26] [INFO] token_jQj5wy1XbLo8qnAR9HVlXHogvrTnsa57
[2018-04-27 14:46:26] [INFO] ===XUNMA RESTURN:False:Session 过期
[2018-04-27 14:46:30] [INFO] itemcode_2760
[2018-04-27 14:46:30] [INFO] token_BZndZlvdgktUEqCtDwb1Lpy5zq8FdY32
[2018-04-27 14:46:30] [INFO] ===XUNMA RESTURN:15719485339;
[2018-04-27 14:46:42] [INFO] 开始获取验证码：15719485339, wechat_register
[2018-04-27 14:46:45] [INFO] 收到消息：NOTION&单笔充值满 50元送 5%单笔充值满100元送10%自动赠送！上不封顶！-------------------------运营商选择 移动、联通或电信，不会出17号段-------------------------QQ群：662853542　-------------------------[End]
[2018-04-27 14:46:45] [INFO] 切分消息：NOTION&单笔充值满 50元送 5%单笔充值满100元送10%自动赠送！上不封顶！-------------------------运营商选择 移动、联通或电信，不会出17号段-------------------------QQ群：662853542　-------------------------
[2018-04-27 14:46:48] [INFO] 收到消息：Null
[2018-04-27 14:46:48] [INFO] 切分消息：Null
[2018-04-27 14:46:51] [INFO] 收到消息：Null
[2018-04-27 14:46:51] [INFO] 切分消息：Null
[2018-04-27 14:46:54] [INFO] 收到消息：Null
[2018-04-27 14:46:54] [INFO] 切分消息：Null
[2018-04-27 14:46:58] [INFO] 收到消息：Null
[2018-04-27 14:46:58] [INFO] 切分消息：Null
[2018-04-27 14:47:01] [INFO] 收到消息：Null
[2018-04-27 14:47:01] [INFO] 切分消息：Null
[2018-04-27 14:47:04] [INFO] 收到消息：MSG&2760&15719485339&【易信验证码】易信验证码为：2073，请勿将验证码提供给他人。[End]
[2018-04-27 14:47:04] [INFO] 切分消息：MSG&2760&15719485339&【易信验证码】易信验证码为：2073，请勿将验证码提供给他人。
[2018-04-27 14:47:04] [INFO] KEY: verify_code_2760_15719485339, Code: 2073
[2018-04-27 15:16:20] [INFO] itemcode_2760
[2018-04-27 15:16:20] [INFO] token_BZndZlvdgktUEqCtDwb1Lpy5zq8FdY32
[2018-04-27 15:16:20] [INFO] ===XUNMA RESTURN:False:Session 过期
[2018-04-27 15:16:24] [INFO] itemcode_2760
[2018-04-27 15:16:24] [INFO] token_4ZgLj4fHUMixrhHarsgAxYngfSXg9E9
[2018-04-27 15:16:24] [INFO] ===XUNMA RESTURN:15719465823;
[2018-04-27 15:16:36] [INFO] 开始获取验证码：15719465823, wechat_register
[2018-04-27 15:16:39] [INFO] 收到消息：NOTION&单笔充值满 50元送 5%单笔充值满100元送10%自动赠送！上不封顶！-------------------------运营商选择 移动、联通或电信，不会出17号段-------------------------QQ群：662853542　-------------------------[End]MSG&2760&15719465823&【易信验证码】易信验证码为：5113，请勿将验证码提供给他人。[End]
[2018-04-27 15:16:39] [INFO] 切分消息：NOTION&单笔充值满 50元送 5%单笔充值满100元送10%自动赠送！上不封顶！-------------------------运营商选择 移动、联通或电信，不会出17号段-------------------------QQ群：662853542　-------------------------
[2018-04-27 15:16:39] [INFO] 切分消息：MSG&2760&15719465823&【易信验证码】易信验证码为：5113，请勿将验证码提供给他人。
[2018-04-27 15:16:39] [INFO] KEY: verify_code_2760_15719465823, Code: 5113
[2018-04-28 17:36:38] [INFO] itemcode_2760
[2018-04-28 17:36:38] [INFO] token_4ZgLj4fHUMixrhHarsgAxYngfSXg9E9
[2018-04-28 17:36:38] [INFO] ===XUNMA RESTURN:False:Session 过期
[2018-04-28 17:36:42] [INFO] itemcode_2760
[2018-04-28 17:36:42] [INFO] token_yjNcoT36ofGsmnlsf2uLMQ9MRglear44
[2018-04-28 17:36:43] [INFO] ===XUNMA RESTURN:False:暂时没有此项目号码，请等会试试...
[2018-04-28 17:36:48] [INFO] itemcode_2760
[2018-04-28 17:36:48] [INFO] token_yjNcoT36ofGsmnlsf2uLMQ9MRglear44
[2018-04-28 17:36:48] [INFO] ===XUNMA RESTURN:False:暂时没有此项目号码，请等会试试...
[2018-04-28 17:36:53] [INFO] itemcode_2760
[2018-04-28 17:36:53] [INFO] token_yjNcoT36ofGsmnlsf2uLMQ9MRglear44
[2018-04-28 17:36:53] [INFO] ===XUNMA RESTURN:False:暂时没有此项目号码，请等会试试...
[2018-04-28 17:36:59] [INFO] itemcode_2760
[2018-04-28 17:36:59] [INFO] token_yjNcoT36ofGsmnlsf2uLMQ9MRglear44
[2018-04-28 17:36:59] [INFO] ===XUNMA RESTURN:False:暂时没有此项目号码，请等会试试...
[2018-04-28 17:37:04] [INFO] itemcode_2760
[2018-04-28 17:37:04] [INFO] token_yjNcoT36ofGsmnlsf2uLMQ9MRglear44
[2018-04-28 17:37:04] [INFO] ===XUNMA RESTURN:False:暂时没有此项目号码，请等会试试...
[2018-04-28 17:37:09] [INFO] itemcode_2760
[2018-04-28 17:37:09] [INFO] token_yjNcoT36ofGsmnlsf2uLMQ9MRglear44
[2018-04-28 17:37:09] [INFO] ===XUNMA RESTURN:False:暂时没有此项目号码，请等会试试...
[2018-04-28 17:37:14] [INFO] itemcode_2760
[2018-04-28 17:37:14] [INFO] token_yjNcoT36ofGsmnlsf2uLMQ9MRglear44
[2018-04-28 17:37:15] [INFO] ===XUNMA RESTURN:False:暂时没有此项目号码，请等会试试...
[2018-04-28 17:37:20] [INFO] itemcode_2760
[2018-04-28 17:37:20] [INFO] token_yjNcoT36ofGsmnlsf2uLMQ9MRglear44
[2018-04-28 17:37:20] [INFO] ===XUNMA RESTURN:False:暂时没有此项目号码，请等会试试...
[2018-04-28 17:37:25] [INFO] itemcode_2760
[2018-04-28 17:37:25] [INFO] token_yjNcoT36ofGsmnlsf2uLMQ9MRglear44
[2018-04-28 17:37:25] [INFO] ===XUNMA RESTURN:False:暂时没有此项目号码，请等会试试...
[2018-04-28 17:37:30] [INFO] itemcode_2760
[2018-04-28 17:37:30] [INFO] token_yjNcoT36ofGsmnlsf2uLMQ9MRglear44
[2018-04-28 17:37:30] [INFO] ===XUNMA RESTURN:False:暂时没有此项目号码，请等会试试...
[2018-04-28 17:37:36] [INFO] itemcode_2760
[2018-04-28 17:37:36] [INFO] token_yjNcoT36ofGsmnlsf2uLMQ9MRglear44
[2018-04-28 17:37:36] [INFO] ===XUNMA RESTURN:False:暂时没有此项目号码，请等会试试...
[2018-04-28 17:37:41] [INFO] itemcode_2760
[2018-04-28 17:37:41] [INFO] token_yjNcoT36ofGsmnlsf2uLMQ9MRglear44
[2018-04-28 17:37:41] [INFO] ===XUNMA RESTURN:False:暂时没有此项目号码，请等会试试...
[2018-04-28 17:52:32] [INFO] itemcode_2760
[2018-04-28 17:52:32] [INFO] token_yjNcoT36ofGsmnlsf2uLMQ9MRglear44
[2018-04-28 17:52:32] [INFO] ===XUNMA RESTURN:13458583954;
[2018-04-28 17:52:43] [INFO] 开始获取验证码：13458583954, wechat_register
[2018-04-28 17:52:47] [INFO] 收到消息：NOTION&单笔充值满 50元送 5%单笔充值满100元送10%自动赠送！上不封顶！-------------------------运营商选择 移动、联通或电信，不会出17号段-------------------------QQ群：662853542　-------------------------[End]MSG&2760&13458583954&【易信验证码】易信验证码为：7675，请勿将验证码提供给他人。[End]
[2018-04-28 17:52:47] [INFO] 切分消息：NOTION&单笔充值满 50元送 5%单笔充值满100元送10%自动赠送！上不封顶！-------------------------运营商选择 移动、联通或电信，不会出17号段-------------------------QQ群：662853542　-------------------------
[2018-04-28 17:52:47] [INFO] 切分消息：MSG&2760&13458583954&【易信验证码】易信验证码为：7675，请勿将验证码提供给他人。
[2018-04-28 17:52:47] [INFO] KEY: verify_code_2760_13458583954, Code: 7675
[2018-04-28 17:55:16] [INFO] itemcode_2760
[2018-04-28 17:55:16] [INFO] token_yjNcoT36ofGsmnlsf2uLMQ9MRglear44
[2018-04-28 17:55:16] [INFO] ===XUNMA RESTURN:13458584933;
[2018-04-28 17:55:27] [INFO] 开始获取验证码：13458584933, wechat_register
[2018-04-28 17:55:30] [INFO] 收到消息：USER&16.971&500&3000&1500&0.8&18.929[End]MSG&2760&13458584933&【易信验证码】易信验证码为：7385，请勿将验证码提供给他人。[End]
[2018-04-28 17:55:30] [INFO] 切分消息：USER&16.971&500&3000&1500&0.8&18.929
[2018-04-28 17:55:30] [INFO] 切分消息：MSG&2760&13458584933&【易信验证码】易信验证码为：7385，请勿将验证码提供给他人。
[2018-04-28 17:55:30] [INFO] KEY: verify_code_2760_13458584933, Code: 7385
[2018-04-28 17:57:07] [INFO] itemcode_2760
[2018-04-28 17:57:07] [INFO] token_yjNcoT36ofGsmnlsf2uLMQ9MRglear44
[2018-04-28 17:57:07] [INFO] ===XUNMA RESTURN:13458585473;
[2018-04-28 17:57:18] [INFO] 开始获取验证码：13458585473, wechat_register
[2018-04-28 17:57:21] [INFO] 收到消息：USER&16.891&500&3000&1500&0.8&18.929[End]MSG&2760&13458585473&【易信验证码】易信验证码为：1348，请勿将验证码提供给他人。[End]
[2018-04-28 17:57:21] [INFO] 切分消息：USER&16.891&500&3000&1500&0.8&18.929
[2018-04-28 17:57:21] [INFO] 切分消息：MSG&2760&13458585473&【易信验证码】易信验证码为：1348，请勿将验证码提供给他人。
[2018-04-28 17:57:21] [INFO] KEY: verify_code_2760_13458585473, Code: 1348
[2018-04-28 18:02:33] [INFO] itemcode_2760
[2018-04-28 18:02:33] [INFO] token_yjNcoT36ofGsmnlsf2uLMQ9MRglear44
[2018-04-28 18:02:33] [INFO] ===XUNMA RESTURN:False:Session 过期
[2018-04-28 18:02:37] [INFO] itemcode_2760
[2018-04-28 18:02:37] [INFO] token_IsbHvoLydTPk7CAlZVejLi8N7qRr3042
[2018-04-28 18:02:37] [INFO] ===XUNMA RESTURN:13458589597;
[2018-04-28 18:02:48] [INFO] 开始获取验证码：13458589597, wechat_register
[2018-04-28 18:02:51] [INFO] 收到消息：NOTION&单笔充值满 50元送 5%单笔充值满100元送10%自动赠送！上不封顶！-------------------------运营商选择 移动、联通或电信，不会出17号段-------------------------QQ群：662853542　-------------------------[End]MSG&2760&13458589597&【易信验证码】易信验证码为：7164，请勿将验证码提供给他人。[End]
[2018-04-28 18:02:51] [INFO] 切分消息：NOTION&单笔充值满 50元送 5%单笔充值满100元送10%自动赠送！上不封顶！-------------------------运营商选择 移动、联通或电信，不会出17号段-------------------------QQ群：662853542　-------------------------
[2018-04-28 18:02:51] [INFO] 切分消息：MSG&2760&13458589597&【易信验证码】易信验证码为：7164，请勿将验证码提供给他人。
[2018-04-28 18:02:51] [INFO] KEY: verify_code_2760_13458589597, Code: 7164
[2018-04-28 18:04:58] [INFO] itemcode_2760
[2018-04-28 18:04:58] [INFO] token_IsbHvoLydTPk7CAlZVejLi8N7qRr3042
[2018-04-28 18:04:58] [INFO] ===XUNMA RESTURN:13458589626;
[2018-04-28 18:05:09] [INFO] 开始获取验证码：13458589626, wechat_register
[2018-04-28 18:05:13] [INFO] 收到消息：USER&16.731&500&3000&1500&0.8&18.929[End]MSG&2760&13458589626&【易信验证码】易信验证码为：2846，请勿将验证码提供给他人。[End]
[2018-04-28 18:05:13] [INFO] 切分消息：USER&16.731&500&3000&1500&0.8&18.929
[2018-04-28 18:05:13] [INFO] 切分消息：MSG&2760&13458589626&【易信验证码】易信验证码为：2846，请勿将验证码提供给他人。
[2018-04-28 18:05:13] [INFO] KEY: verify_code_2760_13458589626, Code: 2846
[2018-04-28 18:10:24] [INFO] itemcode_2760
[2018-04-28 18:10:24] [INFO] token_IsbHvoLydTPk7CAlZVejLi8N7qRr3042
[2018-04-28 18:10:24] [INFO] ===XUNMA RESTURN:15708478474;
[2018-04-28 18:10:36] [INFO] 开始获取验证码：15708478474, wechat_register
[2018-04-28 18:10:39] [INFO] 收到消息：USER&126.651&500&3000&1500&0.8&18.929[End]MSG&2760&15708478474&【易信验证码】易信验证码为：2228，请勿将验证码提供给他人。[End]
[2018-04-28 18:10:39] [INFO] 切分消息：USER&126.651&500&3000&1500&0.8&18.929
[2018-04-28 18:10:39] [INFO] 切分消息：MSG&2760&15708478474&【易信验证码】易信验证码为：2228，请勿将验证码提供给他人。
[2018-04-28 18:10:39] [INFO] KEY: verify_code_2760_15708478474, Code: 2228
[2018-04-28 18:55:52] [INFO] itemcode_2760
[2018-04-28 18:55:52] [INFO] token_IsbHvoLydTPk7CAlZVejLi8N7qRr3042
[2018-04-28 18:55:52] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2018-04-28 18:55:52] [INFO] itemcode_2760
[2018-04-28 18:55:52] [INFO] token_IsbHvoLydTPk7CAlZVejLi8N7qRr3042
[2018-04-28 18:55:52] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2018-04-28 18:55:52] [INFO] itemcode_2760
[2018-04-28 18:55:52] [INFO] token_IsbHvoLydTPk7CAlZVejLi8N7qRr3042
[2018-04-28 18:55:52] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2018-04-28 18:55:52] [INFO] itemcode_2760
[2018-04-28 18:55:52] [INFO] token_IsbHvoLydTPk7CAlZVejLi8N7qRr3042
[2018-04-28 18:55:52] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2018-04-28 18:55:52] [INFO] itemcode_2760
[2018-04-28 18:55:52] [INFO] token_IsbHvoLydTPk7CAlZVejLi8N7qRr3042
[2018-04-28 18:55:52] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2018-04-28 18:55:52] [INFO] itemcode_2760
[2018-04-28 18:55:52] [INFO] token_IsbHvoLydTPk7CAlZVejLi8N7qRr3042
[2018-04-28 18:55:52] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2018-04-28 18:55:52] [INFO] itemcode_2760
[2018-04-28 18:55:52] [INFO] token_IsbHvoLydTPk7CAlZVejLi8N7qRr3042
[2018-04-28 18:55:52] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2018-04-28 18:55:52] [INFO] itemcode_2760
[2018-04-28 18:55:52] [INFO] token_IsbHvoLydTPk7CAlZVejLi8N7qRr3042
[2018-04-28 18:55:52] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2018-04-28 18:55:52] [INFO] itemcode_2760
[2018-04-28 18:55:52] [INFO] token_IsbHvoLydTPk7CAlZVejLi8N7qRr3042
[2018-04-28 18:55:52] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2018-04-28 18:55:52] [INFO] itemcode_2760
[2018-04-28 18:55:52] [INFO] token_IsbHvoLydTPk7CAlZVejLi8N7qRr3042
[2018-04-28 18:55:52] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2018-04-28 18:55:52] [INFO] itemcode_2760
[2018-04-28 18:55:52] [INFO] token_IsbHvoLydTPk7CAlZVejLi8N7qRr3042
[2018-04-28 18:55:52] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2018-04-28 18:55:52] [INFO] itemcode_2760
[2018-04-28 18:55:52] [INFO] token_IsbHvoLydTPk7CAlZVejLi8N7qRr3042
[2018-04-28 18:55:52] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2018-04-28 18:55:52] [INFO] itemcode_2760
[2018-04-28 18:55:52] [INFO] token_IsbHvoLydTPk7CAlZVejLi8N7qRr3042
[2018-04-28 18:55:52] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2018-04-28 18:55:52] [INFO] itemcode_2760
[2018-04-28 18:55:52] [INFO] token_IsbHvoLydTPk7CAlZVejLi8N7qRr3042
[2018-04-28 18:55:52] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2018-04-28 18:55:52] [INFO] itemcode_2760
[2018-04-28 18:55:52] [INFO] token_IsbHvoLydTPk7CAlZVejLi8N7qRr3042
[2018-04-28 18:55:52] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2018-04-28 18:55:52] [INFO] itemcode_2760
[2018-04-28 18:55:52] [INFO] token_IsbHvoLydTPk7CAlZVejLi8N7qRr3042
[2018-04-28 18:55:52] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2018-04-28 18:55:52] [INFO] itemcode_2760
[2018-04-28 18:55:52] [INFO] token_IsbHvoLydTPk7CAlZVejLi8N7qRr3042
[2018-04-28 18:55:52] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2018-04-28 18:55:52] [INFO] itemcode_2760
[2018-04-28 18:55:52] [INFO] token_IsbHvoLydTPk7CAlZVejLi8N7qRr3042
[2018-04-28 18:55:52] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2018-04-28 18:55:52] [INFO] itemcode_2760
[2018-04-28 18:55:52] [INFO] token_IsbHvoLydTPk7CAlZVejLi8N7qRr3042
[2018-04-28 18:55:52] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2018-04-28 18:55:52] [INFO] itemcode_2760
[2018-04-28 18:55:52] [INFO] token_IsbHvoLydTPk7CAlZVejLi8N7qRr3042
[2018-04-28 18:55:52] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2018-04-28 18:55:52] [INFO] itemcode_2760
[2018-04-28 18:55:52] [INFO] token_IsbHvoLydTPk7CAlZVejLi8N7qRr3042
[2018-04-28 18:55:52] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2018-04-28 18:55:52] [INFO] itemcode_2760
[2018-04-28 18:55:52] [INFO] token_IsbHvoLydTPk7CAlZVejLi8N7qRr3042
[2018-04-28 18:55:52] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2018-04-28 18:55:52] [INFO] itemcode_2760
[2018-04-28 18:55:52] [INFO] token_IsbHvoLydTPk7CAlZVejLi8N7qRr3042
[2018-04-28 18:55:52] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2018-04-28 18:55:52] [INFO] itemcode_2760
[2018-04-28 18:55:52] [INFO] token_IsbHvoLydTPk7CAlZVejLi8N7qRr3042
[2018-04-28 18:55:52] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2018-04-28 18:55:52] [INFO] itemcode_2760
[2018-04-28 18:55:52] [INFO] token_IsbHvoLydTPk7CAlZVejLi8N7qRr3042
[2018-04-28 18:55:52] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2018-04-28 18:55:52] [INFO] itemcode_2760
[2018-04-28 18:55:52] [INFO] token_IsbHvoLydTPk7CAlZVejLi8N7qRr3042
[2018-04-28 18:55:52] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2018-04-28 18:55:52] [INFO] itemcode_2760
[2018-04-28 18:55:52] [INFO] token_IsbHvoLydTPk7CAlZVejLi8N7qRr3042
[2018-04-28 18:55:52] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2018-04-28 18:55:52] [INFO] itemcode_2760
[2018-04-28 18:55:52] [INFO] token_IsbHvoLydTPk7CAlZVejLi8N7qRr3042
[2018-04-28 18:55:52] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2018-04-28 18:55:52] [INFO] itemcode_2760
[2018-04-28 18:55:52] [INFO] token_IsbHvoLydTPk7CAlZVejLi8N7qRr3042
[2018-04-28 18:55:52] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2018-04-28 18:55:52] [INFO] itemcode_2760
[2018-04-28 18:55:52] [INFO] token_IsbHvoLydTPk7CAlZVejLi8N7qRr3042
[2018-04-28 18:55:52] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2018-04-28 18:55:58] [INFO] itemcode_2760
[2018-04-28 18:55:58] [INFO] token_IsbHvoLydTPk7CAlZVejLi8N7qRr3042
[2018-04-28 18:55:58] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2018-04-28 18:55:58] [INFO] itemcode_2760
[2018-04-28 18:55:58] [INFO] token_IsbHvoLydTPk7CAlZVejLi8N7qRr3042
[2018-04-28 18:55:58] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2018-04-28 18:55:58] [INFO] itemcode_2760
[2018-04-28 18:55:58] [INFO] token_IsbHvoLydTPk7CAlZVejLi8N7qRr3042
[2018-04-28 18:55:58] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2018-04-28 18:55:58] [INFO] itemcode_2760
[2018-04-28 18:55:58] [INFO] token_IsbHvoLydTPk7CAlZVejLi8N7qRr3042
[2018-04-28 18:55:58] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2018-04-28 18:55:58] [INFO] itemcode_2760
[2018-04-28 18:55:58] [INFO] token_IsbHvoLydTPk7CAlZVejLi8N7qRr3042
[2018-04-28 18:55:58] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2018-04-28 18:55:58] [INFO] itemcode_2760
[2018-04-28 18:55:58] [INFO] token_IsbHvoLydTPk7CAlZVejLi8N7qRr3042
[2018-04-28 18:55:58] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2018-04-28 18:55:58] [INFO] itemcode_2760
[2018-04-28 18:55:58] [INFO] token_IsbHvoLydTPk7CAlZVejLi8N7qRr3042
[2018-04-28 18:55:58] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2018-04-28 18:55:58] [INFO] itemcode_2760
[2018-04-28 18:55:58] [INFO] token_IsbHvoLydTPk7CAlZVejLi8N7qRr3042
[2018-04-28 18:55:58] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2018-04-28 18:55:58] [INFO] itemcode_2760
[2018-04-28 18:55:58] [INFO] token_IsbHvoLydTPk7CAlZVejLi8N7qRr3042
[2018-04-28 18:55:58] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2018-04-28 18:55:58] [INFO] itemcode_2760
[2018-04-28 18:55:58] [INFO] token_IsbHvoLydTPk7CAlZVejLi8N7qRr3042
[2018-04-28 18:55:58] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2018-04-28 18:55:58] [INFO] itemcode_2760
[2018-04-28 18:55:58] [INFO] token_IsbHvoLydTPk7CAlZVejLi8N7qRr3042
[2018-04-28 18:55:58] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2018-04-28 18:55:58] [INFO] itemcode_2760
[2018-04-28 18:55:58] [INFO] token_IsbHvoLydTPk7CAlZVejLi8N7qRr3042
[2018-04-28 18:55:58] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2018-04-28 18:55:58] [INFO] itemcode_2760
[2018-04-28 18:55:58] [INFO] token_IsbHvoLydTPk7CAlZVejLi8N7qRr3042
[2018-04-28 18:55:58] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2018-04-28 18:55:58] [INFO] itemcode_2760
[2018-04-28 18:55:58] [INFO] token_IsbHvoLydTPk7CAlZVejLi8N7qRr3042
[2018-04-28 18:55:58] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2018-04-28 18:55:58] [INFO] itemcode_2760
[2018-04-28 18:55:58] [INFO] token_IsbHvoLydTPk7CAlZVejLi8N7qRr3042
[2018-04-28 18:55:58] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2018-04-28 18:55:58] [INFO] itemcode_2760
[2018-04-28 18:55:58] [INFO] token_IsbHvoLydTPk7CAlZVejLi8N7qRr3042
[2018-04-28 18:55:58] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2018-04-28 18:55:58] [INFO] itemcode_2760
[2018-04-28 18:55:58] [INFO] token_IsbHvoLydTPk7CAlZVejLi8N7qRr3042
[2018-04-28 18:55:58] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2018-04-28 18:55:58] [INFO] itemcode_2760
[2018-04-28 18:55:58] [INFO] token_IsbHvoLydTPk7CAlZVejLi8N7qRr3042
[2018-04-28 18:55:58] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2018-04-28 18:55:58] [INFO] itemcode_2760
[2018-04-28 18:55:58] [INFO] token_IsbHvoLydTPk7CAlZVejLi8N7qRr3042
[2018-04-28 18:55:58] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2018-04-28 18:55:58] [INFO] itemcode_2760
[2018-04-28 18:55:58] [INFO] token_IsbHvoLydTPk7CAlZVejLi8N7qRr3042
[2018-04-28 18:55:58] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2018-04-28 18:55:58] [INFO] itemcode_2760
[2018-04-28 18:55:58] [INFO] token_IsbHvoLydTPk7CAlZVejLi8N7qRr3042
[2018-04-28 18:55:58] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2018-04-28 18:55:58] [INFO] itemcode_2760
[2018-04-28 18:55:58] [INFO] token_IsbHvoLydTPk7CAlZVejLi8N7qRr3042
[2018-04-28 18:55:58] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2018-04-28 18:55:58] [INFO] itemcode_2760
[2018-04-28 18:55:58] [INFO] token_IsbHvoLydTPk7CAlZVejLi8N7qRr3042
[2018-04-28 18:55:58] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2018-04-28 18:55:58] [INFO] itemcode_2760
[2018-04-28 18:55:58] [INFO] token_IsbHvoLydTPk7CAlZVejLi8N7qRr3042
[2018-04-28 18:55:58] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2018-04-28 18:55:58] [INFO] itemcode_2760
[2018-04-28 18:55:58] [INFO] token_IsbHvoLydTPk7CAlZVejLi8N7qRr3042
[2018-04-28 18:55:58] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2018-04-28 18:55:58] [INFO] itemcode_2760
[2018-04-28 18:55:58] [INFO] token_IsbHvoLydTPk7CAlZVejLi8N7qRr3042
[2018-04-28 18:55:58] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2018-04-28 18:55:58] [INFO] itemcode_2760
[2018-04-28 18:55:58] [INFO] token_IsbHvoLydTPk7CAlZVejLi8N7qRr3042
[2018-04-28 18:55:58] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2018-04-28 18:55:58] [INFO] itemcode_2760
[2018-04-28 18:55:58] [INFO] token_IsbHvoLydTPk7CAlZVejLi8N7qRr3042
[2018-04-28 18:55:58] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2018-04-28 18:55:58] [INFO] itemcode_2760
[2018-04-28 18:55:58] [INFO] token_IsbHvoLydTPk7CAlZVejLi8N7qRr3042
[2018-04-28 18:55:58] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2018-04-28 18:55:58] [INFO] itemcode_2760
[2018-04-28 18:55:58] [INFO] token_IsbHvoLydTPk7CAlZVejLi8N7qRr3042
[2018-04-28 18:55:58] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2018-04-28 18:56:03] [INFO] itemcode_2760
[2018-04-28 18:56:03] [INFO] token_IsbHvoLydTPk7CAlZVejLi8N7qRr3042
[2018-04-28 18:56:04] [INFO] ===XUNMA RESTURN:False:Session 过期
[2018-04-28 18:56:08] [INFO] itemcode_2760
[2018-04-28 18:56:08] [INFO] token_2I3Bw9VI2t6GPksPtioYpoh5yYU3Iw13
[2018-04-28 18:56:18] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 91, in GetPhoneNumber
    response = conn.getresponse()
  File "/usr/lib/python2.7/httplib.py", line 1136, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer

[2018-04-28 18:56:18] [INFO] itemcode_2760
[2018-04-28 18:56:18] [INFO] token_2I3Bw9VI2t6GPksPtioYpoh5yYU3Iw13
[2018-04-28 18:56:18] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2018-04-28 18:56:18] [INFO] itemcode_2760
[2018-04-28 18:56:18] [INFO] token_2I3Bw9VI2t6GPksPtioYpoh5yYU3Iw13
[2018-04-28 18:56:18] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2018-04-28 18:56:18] [INFO] itemcode_2760
[2018-04-28 18:56:18] [INFO] token_2I3Bw9VI2t6GPksPtioYpoh5yYU3Iw13
[2018-04-28 18:56:18] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2018-04-28 18:56:18] [INFO] itemcode_2760
[2018-04-28 18:56:18] [INFO] token_2I3Bw9VI2t6GPksPtioYpoh5yYU3Iw13
[2018-04-28 18:56:18] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2018-04-28 18:56:18] [INFO] itemcode_2760
[2018-04-28 18:56:18] [INFO] token_2I3Bw9VI2t6GPksPtioYpoh5yYU3Iw13
[2018-04-28 18:56:18] [ERROR] Traceback (most recent call last):
  File "/home/zunyun/workspace/TaskConsole/smsCode/client_xunma.py", line 90, in GetPhoneNumber
    conn.request("GET", path)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[2018-04-28 18:56:18] [INFO] itemcode_2760
[2018-04-28 18:56:18] [INFO] token_2I3Bw9VI2t6GPksPtioYpoh5yYU3Iw13
[2018-04-28 18:56:18] [INFO] ===XUNMA RESTURN:False:Session 过期
[2018-04-28 18:56:22] [INFO] itemcode_2760
[2018-04-28 18:56:22] [INFO] token_qBn4FIrFlFImrZWrBDge70JD7A7F4j6
[2018-04-28 18:56:24] [INFO] ===XUNMA RESTURN:False:暂时没有此项目号码，请等会试试...
[2018-04-28 18:56:29] [INFO] itemcode_2760
[2018-04-28 18:56:29] [INFO] token_qBn4FIrFlFImrZWrBDge70JD7A7F4j6
[2018-04-28 18:56:30] [INFO] ===XUNMA RESTURN:15719450395;
[2018-04-28 19:17:58] [INFO] itemcode_2760
[2018-04-28 19:17:58] [INFO] token_qBn4FIrFlFImrZWrBDge70JD7A7F4j6
[2018-04-28 19:17:58] [INFO] ===XUNMA RESTURN:False:Session 过期
[2018-04-28 19:18:02] [INFO] itemcode_2760
[2018-04-28 19:18:02] [INFO] token_vfnGbKA4nC0JiLsPrYCM50JizrRUQ663
[2018-04-28 19:18:02] [INFO] ===XUNMA RESTURN:15719450395;
[2018-04-28 19:18:46] [INFO] 开始获取验证码：15719450395, wechat_register
[2018-04-28 19:18:49] [INFO] 收到消息：NOTION&单笔充值满 50元送 5%单笔充值满100元送10%自动赠送！上不封顶！-------------------------运营商选择 移动、联通或电信，不会出17号段-------------------------QQ群：662853542　-------------------------[End]
[2018-04-28 19:18:49] [INFO] 切分消息：NOTION&单笔充值满 50元送 5%单笔充值满100元送10%自动赠送！上不封顶！-------------------------运营商选择 移动、联通或电信，不会出17号段-------------------------QQ群：662853542　-------------------------
[2018-04-28 19:18:52] [INFO] 收到消息：Null
[2018-04-28 19:18:52] [INFO] 切分消息：Null
[2018-04-28 19:18:55] [INFO] 收到消息：Null
[2018-04-28 19:18:55] [INFO] 切分消息：Null
[2018-04-28 19:18:58] [INFO] 收到消息：Null
[2018-04-28 19:18:58] [INFO] 切分消息：Null
[2018-04-28 19:19:02] [INFO] 收到消息：Null
[2018-04-28 19:19:02] [INFO] 切分消息：Null
[2018-04-28 19:19:05] [INFO] 收到消息：Null
[2018-04-28 19:19:05] [INFO] 切分消息：Null
[2018-04-28 19:19:08] [INFO] 收到消息：Null
[2018-04-28 19:19:08] [INFO] 切分消息：Null
[2018-04-28 19:19:11] [INFO] 收到消息：Null
[2018-04-28 19:19:11] [INFO] 切分消息：Null
[2018-04-28 19:19:14] [INFO] 收到消息：Null
[2018-04-28 19:19:14] [INFO] 切分消息：Null
[2018-04-28 19:19:17] [INFO] 收到消息：Null
[2018-04-28 19:19:17] [INFO] 切分消息：Null
[2018-04-28 19:19:20] [INFO] 收到消息：Null
[2018-04-28 19:19:20] [INFO] 切分消息：Null
[2018-04-28 19:19:24] [INFO] 收到消息：Null
[2018-04-28 19:19:24] [INFO] 切分消息：Null
[2018-04-28 19:19:27] [INFO] 收到消息：Null
[2018-04-28 19:19:27] [INFO] 切分消息：Null
[2018-04-28 19:19:30] [INFO] 收到消息：Null
[2018-04-28 19:19:30] [INFO] 切分消息：Null
[2018-04-28 19:19:33] [INFO] 收到消息：Null
[2018-04-28 19:19:33] [INFO] 切分消息：Null
[2018-04-28 19:19:36] [INFO] 收到消息：Null
[2018-04-28 19:19:36] [INFO] 切分消息：Null
[2018-04-28 19:19:39] [INFO] 收到消息：Null
[2018-04-28 19:19:39] [INFO] 切分消息：Null
[2018-04-28 19:19:43] [INFO] 收到消息：Null
[2018-04-28 19:19:43] [INFO] 切分消息：Null
[2018-04-28 19:19:46] [INFO] 收到消息：Null
[2018-04-28 19:19:46] [INFO] 切分消息：Null
[2018-04-28 19:44:40] [INFO] itemcode_2760
[2018-04-28 19:44:40] [INFO] token_vfnGbKA4nC0JiLsPrYCM50JizrRUQ663
[2018-04-28 19:44:40] [INFO] ===XUNMA RESTURN:False:Session 过期
[2018-04-28 19:44:44] [INFO] itemcode_2760
[2018-04-28 19:44:44] [INFO] token_XW3VjOGOM2l5wlOP9Ee6jHGcwQvAru49
[2018-04-28 19:44:44] [INFO] ===XUNMA RESTURN:15719465823;
[2018-04-28 19:45:52] [INFO] 开始获取验证码：15719465823, wechat_register
[2018-04-28 19:45:55] [INFO] 收到消息：NOTION&单笔充值满 50元送 5%单笔充值满100元送10%自动赠送！上不封顶！-------------------------运营商选择 移动、联通或电信，不会出17号段-------------------------QQ群：662853542　-------------------------[End]MSG&2760&15719465823&【易信验证码】易信验证码为：6652，请勿将验证码提供给他人。[End]
[2018-04-28 19:45:55] [INFO] 切分消息：NOTION&单笔充值满 50元送 5%单笔充值满100元送10%自动赠送！上不封顶！-------------------------运营商选择 移动、联通或电信，不会出17号段-------------------------QQ群：662853542　-------------------------
[2018-04-28 19:45:55] [INFO] 切分消息：MSG&2760&15719465823&【易信验证码】易信验证码为：6652，请勿将验证码提供给他人。
[2018-04-28 19:45:55] [INFO] KEY: verify_code_2760_15719465823, Code: 6652
[2018-04-28 19:53:14] [INFO] itemcode_2760
[2018-04-28 19:53:14] [INFO] token_XW3VjOGOM2l5wlOP9Ee6jHGcwQvAru49
[2018-04-28 19:53:14] [INFO] ===XUNMA RESTURN:13458584933;
[2018-04-28 19:53:37] [INFO] 开始获取验证码：13458584933, wechat_register
[2018-04-28 19:53:41] [INFO] 收到消息：USER&125.851&500&3000&1500&0.8&18.929[End]
[2018-04-28 19:53:41] [INFO] 切分消息：USER&125.851&500&3000&1500&0.8&18.929
[2018-04-28 19:53:44] [INFO] 收到消息：MSG&2760&13458584933&【易信验证码】易信验证码为：8111，请勿将验证码提供给他人。[End]
[2018-04-28 19:53:44] [INFO] 切分消息：MSG&2760&13458584933&【易信验证码】易信验证码为：8111，请勿将验证码提供给他人。
[2018-04-28 19:53:44] [INFO] KEY: verify_code_2760_13458584933, Code: 8111
